user: hfwittmann

models:
  falcon:
    general: nomic.ai/GPT4All/ggml-model-gpt4all-falcon-q4_0.bin
    userpaths:
      jlourier: /Users/jlourier/Library/Application Support/
      hfwittmann: /home/hfwittmann/.local/share/
    user_local_path: falcon["userpaths"][f"{user}"] + falcon["general"]
  
embeddings:
  path: data/03_primary/embeddings
  collections: ['OpenAIEmbeddings', 'FalconEmbeddings']

llms:
  evaluator: OpenAILLM
  collections: ['OpenAILLM', 'FalconLLM']

url: https://www.lufthansa-industry-solutions.com/de-en/
question: Who is Bernhard Kube?

chat:
  embeddings:
    path: data/03_primary/embeddings
    collections: ['OpenAIEmbeddings', 'FalconEmbeddings']
  llms:
    collections: ['OpenAILLM']

  questions:
    - Who is Bernhard Kube?
    - What is his role at Lufthansa?

